### ISSUE TITLE
Can't reorder on User listing

### ISSUE THREAD

**Issue by pierrestoffe** [mmikkel/CpSortableCustomColumns-Craft#5]
Hello,

Your plugin just saved me a few hours so thanks! I just have one issue with the user listing, where I can't sort users based on a column's content: see [this video](http://quick.as/gdgwfz0r1). That column was added using your plugin.

Do you have any idea why this might occur?
Thanks.

**Comment by mmikkel** [comment]
Thanks for reporting, @pierrestoffe – this should be fixed in version 1.1.1.

**Comment by pierrestoffe** [comment]
Thanks!
