### ISSUE TITLE
Bug with Commerce active/inactive carts view

### ISSUE THREAD

**Issue by bossanova808** [mmikkel/CpSortableCustomColumns-Craft#8]
Hi

This breaks the active/inactive carts vie in Craft Commerce

I believe you're wrapping a whole query and adding an orderby clause - which is rasing

`2016/06/29 04:43:15 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'dateUpdated' in order clause is ambiguous.`

...because it needs to be orders.dateUpdated to be unambiguous.

Well that's based on what Luke said :)

I haven't had a chance to dig in & try and fix (I'm launching something Friday) - but thought I'd raise this in case it was an easy fix for you!

**Comment by bossanova808** [comment]
Further info - the bug only appear with Mysql 5.5, on 5.7 it does not get raised.

(The bug results in nothing being shown in the view and the 'an error has occured' labels at the top)

**Comment by mmikkel** [comment]
Hey @bossanova808, sorry for the late reply and thanks for reporting. I'll look at this ASAP.

**Comment by bossanova808** [comment]
Luke knows about it and mentioned maybe doing a PR - I think if you ask him he'll probably have a quick solve for it.

**Comment by terryupton** [comment]
I have experience this issue too. Do you have an ETA on a fix at all?

Thanks.

**Comment by lukeholder** [comment]
Looks like it is only affecting the active and inactive cart screens, because those _sources_ have a `dateUpdated` criteria attribute built into them.

**Comment by mmikkel** [comment]
Hi gents, sorry about the delay on this one. I've figured out what's happening here, and will hopefully have a patch out very soon. Thanks for contributing!

**Comment by terryupton** [comment]
Hi @mmikkel any update on this at all? I am nearing releasing a Craft Commerce site soon. :-)

**Comment by engram-design** [comment]
If anyone is still looking for a temp fix for this, its a little added JS hack. At https://github.com/mmikkel/CpSortableCustomColumns-Craft/blob/master/cpsortcols/resources/cpsortcols.js#L102 add the following:

```
if ($('body').hasClass('commerceordersindex') && attribute == 'dateUpdated') {
    attribute = 'orders.dateUpdated';
    $header.attr('data-attribute', attribute).data('attribute', attribute);
}
```

**Comment by mmikkel** [comment]
I've added the fix from @engram-design to [v. 1.1.2](https://github.com/mmikkel/CpSortableCustomColumns-Craft/releases/tag/v.1.1.2).
